[package]
name = "algorithm"
version = "0.1.0"
authors = ["hamada <hamada@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srand = "0.4.0"
libc = "0.2"

[[bin]]
name = "bsrch"
path = "src/bsrch.rs"
